### ISSUE TITLE
[Bug] 调用google搜索异常

### ISSUE THREAD

**Issue by sparkssssssssss** [Hk-Gosuto/ChatGPT-Next-Web-LangChain#272]
### Bug Description
重新开一个对话,就正常的.所以感觉是触发了什么bug

![Snipaste_2024-06-01_15-34-01](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/143824822/c3883454-2cd1-4c93-8b7f-d224e3aec43e)

对话框内返回,部署在海外vps网络应该不是问题

```json
{
  "error": true,
  "message": "[object Object]"
}
```

错误日志
````
[handleChainError] s [Error]: Failed to parse tool arguments from chat model response. Text: "[{"id":"call_3WGii4SpdT1NgUgvGIifPsCV","type":"function","function":{"name":"google_custom_search","parameters":{"type":"","properties":null,"required":null}}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":"{"}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":" \""}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":"input"}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":"\":"}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":" \""}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":"June"}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":" "}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":"1"}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":" holidays"}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":"\""}},{"type":"","function":{"name":"","parameters":{"type":"","properties":null,"required":null},"arguments":" }"}}]". SyntaxError: Unexpected end of JSON input
    at eT.parseAIMessage (/app/.next/server/app/api/langchain/tool/agent/nodejs/route.js:3:57)
    at eT.parseResult (/app/.next/server/app/api/langchain/tool/agent/nodejs/route.js:2:99)
    at e._callWithConfig (/app/.next/server/chunks/4598.js:52:20901)
    at eT._callWithConfig (/app/.next/server/chunks/4598.js:52:40256)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eT._streamIterator (/app/.next/server/chunks/4598.js:52:39455)
    at async eT.transform (/app/.next/server/chunks/4598.js:52:42074)
    at async L._streamIterator (/app/.next/server/chunks/4598.js:55:9141) {
  llmOutput: undefined,
  observation: undefined,
  sendToLLM: false
} writer error
````

### Steps to Reproduce

不知道如何复现,

### Expected Behavior

正常返回搜索内容

### Deployment Method

- [] Docker

**Comment by Hk-Gosuto** [comment]
看起来像是模型的入参有问题，所有支持 function call 的模型都这样么？

**Comment by gcalabria** [comment]
Are you using azure?

**Comment by sparkssssssssss** [comment]
请问下,这个也是因为不支持funciton call吗,之前正常的api,这两天一个都不行了,我也不知道是否是上游的问题.
````
{
  "error": true,
  "message": "400 Invalid schema for function 'google_custom_search': None is not of type 'array'. (request id: 20240609202145290032819xszwXVuX) (request id: 20240609202145288807174eiLv7eVB) (request id: 20240609202145211999335zxfrT6Wd) (request id: 202406092021445731433360EXS9eLF) (request id: 2024060920214426475172543682865)"
}

**Comment by Hk-Gosuto** [comment]
这个看起来是中转服务处理参数相关的问题，比如之前就遇到过 one-api 转发的 azure 服务时部分模型无法正常使用 function call。

**Comment by Hk-Gosuto** [comment]
如果想稳定一些，也可以使用 openrouter 和 azure 之类的服务，第三方的中转服务有时候会有一些莫名其妙的问题。

**Comment by sparkssssssssss** [comment]
> 如果想稳定一些，也可以使用 openrouter 和 azure 之类的服务，第三方的中转服务有时候会有一些莫名其妙的问题。

好的,了解了,谢谢
